config/routes.rb
Rails.application.routes.draw do

  root to: 'photos#main'
  get '/photos', to: 'photos#index', as: :photos
  post '/photos', to: 'photos#create'
  get '/photos/new', to: 'photos#new', as: :new_photo
  get '/photos/ranked', to: 'photos#ranked', as: :ranked
  get '/photos/:id', to: 'photos#show', as: :photo
  delete '/photos/:id', to: 'photos#destroy'
  get '/photos/by/:user_id', to: 'photos#other_user', as: :other_user_photos

  get '/review', to: 'reviews#index', as: :review
  post '/review/:id', to: 'reviews#create', as: :new_review

  get '/sign-up', to: 'users#sign_up', as: :sign_up
  post '/sign-up', to: 'users#create'
  get '/sign-out', to: 'users#sign_out', as: :sign_out
  get '/sign-in', to: 'users#sign_in', as: :sign_in
  post '/sign-in', to: 'users#sign_in_user'
  get '/account', to: 'users#account', as: :account
  patch '/account', to: 'users#update'
  patch '/account/email', to: 'users#update_email', as: :update_email

end

app/models/photo.rb
class Photo < ActiveRecord::Base

  mount_uploader :image_file, ImageFileUploader

  validates :image_file, presence: true

  has_many :reviews, dependent: :destroy
  attr_readonly :reviews_count

  belongs_to :user

end

app/models/review.rb
class Review < ActiveRecord::Base

  validates :rating, presence: true
  validates :user_id, uniqueness: { scope: :photo_id }
  validate :cannot_review_your_own_photos
  belongs_to :photo, counter_cache: true
  belongs_to :user

  def cannot_review_your_own_photos
    if photo.user_id == user_id
      errors.add(:review, "can't review your own photo")
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  validates :email, presence: true, uniqueness: true, format: { with: /\w@\w/ }
  validates :username, presence: true, uniqueness: true

  has_many :photos, dependent: :destroy
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def main
    if current_user
      redirect_to photos_path
    end
  end

  def index
    @photos = current_user.photos
  end

  def new
  end

  def create
    @photo = current_user.photos.build(params.require(:photo).permit(:description, :image_file))
    if @photo.save
      redirect_to photos_path, notice: "The photo was successfully added!"
    else
      render :new
    end
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def ranked
    @photos =
      Photo
        .joins("LEFT OUTER JOIN reviews ON photos.id = reviews.photo_id")
        .select("photos.id, photos.user_id, description, image_file, coalesce(sum(reviews.rating), 0) as sum")
        .group("photos.id")
        .order("sum DESC")
  end

  def destroy
    @photo = current_user.photos.find(params[:id])
    @photo.destroy
    redirect_to photos_path, notice: "The photo was deleted!"
  end

  def other_user
    @user = User.find(params[:user_id])
    @photos = @user.photos
    if @user.id == current_user.id
      redirect_to photos_path
    end
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    photo_ids_reviewed_by_user = Review.where(user_id: current_user.id).pluck(:photo_id)
    photos_for_review = Photo.where.not(id: photo_ids_reviewed_by_user, user_id: current_user.id)
    @photo = photos_for_review.sample
    @review = Review.new
  end

  def create
    @photo = Photo.find(params[:id])
    @review = current_user.reviews.build(params.require(:review).permit(:comment, :rating))
    @review.photo_id = @photo.id
    if @review.save
      ImageMailer.notify(@photo.user_id, @review.id).deliver_now if @photo.user.notification
      ImageMailer.rate(current_user.id, @review.id).deliver_now if current_user.notification
      redirect_to review_path, notice: "Thanks for the review!"
    else
      render :index
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def sign_up
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:username, :email, :password, :password_confirmation))
    if @user.save
      session[:user_id] = @user.id
      redirect_to photos_path, notice: "Welcome!"
    else
      render :sign_up
    end
  end

  def sign_out
    session.delete(:user_id)
    redirect_to root_path
  end

  def sign_in
    @user = User.new
  end

  def sign_in_user
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to photos_path, notice: "Welcome back!"
    else
      redirect_to sign_in_path, notice: "Wrong username or password, try again!"
    end
  end

  def account
    @user = User.new
  end

  def update
    if current_user.notification
      current_user.notification = false
    else
      current_user.notification = true
    end
    current_user.save
    ImageMailer.subscribe(current_user.id).deliver_now if current_user.notification
    redirect_to account_path, notice: "Email settings updated!"
  end

  def update_email
    current_user.email = params[:user][:email]
    if current_user.save
      redirect_to account_path, notice: "Email was updated!"
    else
      @user = current_user
      render :account
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(email)
    hashed_email = Digest::MD5.hexdigest(email.downcase.strip)
    image_tag "http://www.gravatar.com/avatar/#{hashed_email}?s=50.jpg", alt: "Profile Photo", class: "grav"
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Image Rating</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

  <% if current_page?("/") %>
    <body class="background">
  <% else %>
    <body>
   <% end %>

  <nav class="navbar navbar-inverse">
    <div class="container">
      <div class="navbar-header">
        <% if !current_user %>
          <%= link_to image_tag("https://s3-us-west-2.amazonaws.com/image-rating-production/camera.png", class: "navbar-brand img"), root_path %>
        <% else %>
          <%= link_to image_tag("https://s3-us-west-2.amazonaws.com/image-rating-production/camera.png", class: "navbar-brand img"), photos_path %>
        <% end %>
        <button class="navbar-toggle collapsed" data-toggle="collapse" data-target=".menu-wrapper">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>

      <div class="menu-wrapper collapse navbar-collapse">
        <div class="navbar-right">
          <ul class="nav navbar-nav">
            <% if current_user %>
              <li><%= link_to "Add Photo", new_photo_path %></li>
              <li><%= link_to "Review Photo", review_path %></li>
              <li><%= link_to "Ranked Photos", ranked_path %></li>
              <li><%= link_to "My Account", account_path %></li>
              <li><%= link_to "Sign Out", sign_out_path %></li>
            <% else %>
              <li><%= link_to "Sign In", sign_in_path, class: "navbar-brand signin" %></li>
              <li><%= link_to "Sign Up", sign_up_path, class: "navbar-brand signup" %></li>
            <% end %>
          </ul>
        </div>
      </div>

    </div>
  </nav>

  <% if flash[:notice] %>
    <div class="col-lg-6 col-lg-offset-3 text-center alert alert-info">
      <%= flash[:notice] %>
    </div>
  <% end %>

<%= yield %>

</body>
</html>

app/views/photos/_gravatar.html.erb
<%= link_to gravatar_for(photo.user.email), other_user_photos_path(photo.user.id) %>
<%= link_to photo.user.username.capitalize, other_user_photos_path(photo.user.id) %>

app/views/photos/_show_all_photos.html.erb
<div class="row">
  <% @photos.in_groups_of(3, false).each do |group| %>
    <div class="row">
      <% group.each do |photo| %>
        <div class="photo col-sm-4">
          <%= link_to image_tag(photo.image_file.url(:square)), photo_path(photo.id) %>
          <h2 class="text-center"><%= photo.description %></h2>
          <% if photo.description.blank? %>
            <h2 class="random"></h2>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/photos/index.html.erb
<div class="container">
  <div class="clear"></div>
  <%= render "show_all_photos" %>
</div>

app/views/photos/main.html.erb
<div class="container">
  <h1 class="text-center home jumbotron main">Store, Share, Peer Review Photos</h1>
</div>

app/views/photos/new.html.erb
<div class="container">

  <div class="row">
    <h1 class="col-lg-6 col-lg-offset-3 text-center">Add Photo</h1>
  </div>

  <%= render "users/error_messages", object: @photo %>

  <%= form_tag photos_path, class: "form-horizontal", multipart: true do %>
    <div class="form-group">
      <div class="col-lg-3 col-lg-offset-3 text-center">
        <%= label_tag :image_file %>
      </div>
      <%= file_field_tag "photo[image_file]" %>
    </div>
    <div class="form-group">
      <div class="col-lg-3 col-lg-offset-3 text-center">
        <%= label_tag :description %>
      </div>
      <%= text_area_tag "photo[description]" %>
    <div class="col-lg-2 col-lg-offset-5">
      <%= submit_tag "Add Photo", class: "btn btn-block btn-success" %>
    </div>
  <% end %>
</div>

app/views/photos/other_user.html.erb
<div class="container">
  <h1 class="home text-center rev">Photos by <%= @user.username.capitalize %></h1>
  <%= render "show_all_photos" %>
</div>

app/views/photos/ranked.html.erb
<div class="container">
  <h1 class="text-center rev">Photos sorted by rating</h2>
  <% @photos.each do |photo| %>
    <div class="row">
      <div class="col-sm-9">
        <%= link_to image_tag(photo.image_file.url(:preview), class: "show"), photo_path(photo.id) %>
      </div>
      <div class="col-sm-3">
        <%= render "photos/gravatar", photo: photo %>
        <div>Thumbs up: <%= photo.reviews.where(rating: 1).count %></div>
        <div>Meh: <%= photo.reviews.where(rating: 0).count %></div>
        <div>Thumbs down: <%= photo.reviews.where(rating: -1).count %></div>
      </div>
    </div>
    </br>
  <% end %>
</div>

app/views/photos/show.html.erb
<div class="container">
  <div class="row clear">
    <div class="col-sm-9">
      <%= image_tag @photo.image_file.url(:preview), class: "show" %>
      <h3><%= @photo.description %></h3>
    </div>
    <% if current_user %>
      <div class="col-sm-3">
        <% if @photo.user_id != current_user.id %>
          <%= render "photos/gravatar", photo: @photo %>
        <% else %>
          <%= form_tag photo_path(@photo.id), method: "DELETE" do %>
            <%= submit_tag "Remove", data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
          <% end %>
        <% end %>
        <% if @photo.reviews.present? %>
          <h3>Comments</h3>
        <% end %>
        <% @photo.reviews.each do |review| %>
          <% if review.comment.present? %>
            <div class="iconDetails">
              <%= link_to gravatar_for(review.user.email), other_user_photos_path(review.user_id) %>
            </div>
            <div class="name">
              <%= link_to review.user.username.capitalize, other_user_photos_path(review.user_id) %>
            </div>
            <div class="name">
              <%= review.comment %>
            </div>
            </br>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/reviews/index.html.erb
<div class="container">
  <% if @photo %>
    <h1 class="text-center home rev">Review this image</h1>
    <%= render "users/error_messages", object: @review %>

    <div class="col-sm-8">
      <%= link_to image_tag(@photo.image_file.url(:preview), class: "border"), photo_path(@photo.id) %>
    </div>

    <div class="col-sm-4">
      <div class="review">
        Photo by: <%= render "photos/gravatar", photo: @photo %>
      </div>
      <% if @photo.description.present? %>
        <div class="desc"><div class="ph">Description of the photo: </div><%= @photo.description %></div>
      <% end %>
      <%= form_tag new_review_path(@photo.id) do %>
        <%= text_area_tag "review[comment]", nil, class: "col-sm-12 input-lg", placeholder: "leave your comment here" %>
        <%= radio_button_tag("review[rating]", -1) %>
        <%= label_tag("review_rating_-1", "thumbs down") %>
        <%= radio_button_tag("review[rating]", 0) %>
        <%= label_tag("review_rating_0", "meh") %>
        <%= radio_button_tag("review[rating]", 1) %>
        <%= label_tag("review_rating_1", "thumbs up") %>
        <%= submit_tag "Review", class: "btn btn-block btn-success" %>
      <% end %>
    </div>
  <% else %>
    <h1 class="text-center home">No images to review</h1>
  <% end %>
  <br>
</div>

app/views/users/_error_messages.html.erb
<% if object %>
  <ul class="list-unstyled">
    <% object.errors.each do |column, error_message| %>
      <div class="row">
        <li class="col-lg-6 col-lg-offset-3 text-center alert alert-danger"><%= column %> <%= error_message %></li>
      </div>
    <% end %>
  </ul>
<% end %>

app/views/users/account.html.erb
<div class="container">
<h1 class="home text-center"></h1>

  <%= render "error_messages", object: @user %>

  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <div class="jumbotron">
        <h1 class="text-center"><%= gravatar_for(current_user.email) %></h1>
        <h2 class="text-center"><%= current_user.username.capitalize %></h2>
        <h3 class="text-center"><%= current_user.email %></h3>

        <%= form_tag update_email_path, method: "PATCH", class: "form-inline" do %>
          <div class="form-group clear col-sm-offset-2">
            <%= text_field_tag "user[email]", @user.email, placeholder: "user@example.com" %>
            <%= submit_tag "Update email", class: "btn btn-success" %>
          </div>
        <% end %>

        <%= form_tag account_path, method: "PATCH", class: "form-inline" do %>
          <% if current_user.notification %>
            <div class="form-group clear col-sm-offset-1">
              <%= label_tag "Don't want to receive any more emails?" %>
              <%= submit_tag "Unsubscribe", class: "btn" %>
            </div>
          <% else %>
            <div class="form-group clear col-sm-offset-1">
              <%= label_tag "Would you like to receive updates?" %>
              <%= submit_tag "Get Notifications", class: "btn" %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/users/sign_in.html.erb
<div class="container">

  <div class="row">
    <h1 class="col-lg-6 col-lg-offset-3 text-center">Sign In</h1>
  </div>

  <%= form_tag sign_in_path, class: "form-horizontal" do %>
    <div class="form-group">
      <div class="col-lg-3 col-lg-offset-3 text-center">
        <%= label_tag :username %>
      </div>
      <%= text_field_tag :username, nil, class: "col-lg-2", placeholder: "username" %>
    </div>
    <div class="form-group">
      <div class="col-lg-3 col-lg-offset-3 text-center">
        <%= label_tag :password %>
      </div>
      <%= password_field_tag :password, nil, class: "col-lg-2", placeholder: "password" %>
    </div>
    <div class="col-lg-2 col-lg-offset-5">
      <%= submit_tag "Sign In", class: "btn btn-block btn-success" %>
    </div>
  <% end %>

</div>

app/views/users/sign_up.html.erb
<div class="container">

  <div class="row">
    <h1 class="col-lg-6 col-lg-offset-3 text-center">Sign Up</h1>
  </div>

  <%= render "error_messages", object: @user %>

  <%= form_tag sign_up_path, class: "form-horizontal" do %>
    <div class="form-group">
      <div class="col-lg-3 col-lg-offset-3 text-center">
        <%= label_tag "username" %>
      </div>
      <%= text_field_tag "user[username]", @user.username, class: "col-lg-2", placeholder: "username" %>
    </div>
    <div class="form-group">
      <div class="col-lg-3 col-lg-offset-3 text-center">
        <%= label_tag "e-mail" %>
      </div>
      <%= text_field_tag "user[email]", @user.email, class: "col-lg-2", placeholder: "user@example.com" %>
    </div>
    <div class="form-group">
      <div class="col-lg-3 col-lg-offset-3 text-center">
        <%= label_tag :password %>
      </div>
      <%= password_field_tag "user[password]", nil, class: "col-lg-2", placeholder: "password" %>
    </div>
    <div class="form-group">
      <div class="col-lg-3 col-lg-offset-3 text-center">
        <%= label_tag "confirm your password" %>
      </div>
      <%= password_field_tag "user[password_confirmation]", nil, class: "col-lg-2", placeholder: "password" %>
    </div>
    <div class="col-lg-2 col-lg-offset-5">
      <%= submit_tag "Sign Up", class: "btn btn-block btn-success" %>
    </div>
  <% end %>

</div>